### ISSUE TITLE
Uniqueidentifier datatype issue

### ISSUE THREAD

**Issue by WalterW** [DarioN1/SPToCore#1]
it cames out like the following

😂

![image](https://user-images.githubusercontent.com/1876703/81819072-6f4e7300-9561-11ea-8e3b-f26172125a01.png)

**Comment by DarioN1** [comment]
Hi Walter ! I will fix it ASAP today... Come back soon 😄

**Comment by DarioN1** [comment]
Ok, its now fixed, now it manage also uniqueidentifier.
Thanks to support Walter !
