### ISSUE TITLE
stored procedure that use a temp table

### ISSUE THREAD

**Issue by amccool** [DarioN1/SPToCore#4]
I'm getting exceptions like this:
```
EXCEPTION 1 / 5: PrAudioPageButtonGet - The metadata could not be determined because statement 'INSERT INTO #tmpTable(AudioPageButtonId,ButtonName,ButtonLabel,ButtonColor,ButtonActionName,ButtonAc' in procedure 'PrAudioPageButtonGet' uses a temp table.
```

I havent reviewed your code, but I would think you need to get the schema of the dynamic temp table?

**Comment by amccool** [comment]
BTW ❤️  the 
`            public WTF?! BlinkCadenceId { get; set; }`

**Comment by DarioN1** [comment]
Hi @amccool ! Sorry for the delay... Temporary tables are not managed even in linqToSql if I remember well...
You have to use table variable instead and it will work 100%

Please check this:

https://www.sqlshack.com/the-table-variable-in-sql-server/

Can you tell me which is the type of BlinkCadenceId in your table ?
May be not all data types are managed...

**Comment by amccool** [comment]
I converted the Stored Proc to a table variable, which resolved the issue.  As for the WTF missing data type, I found about 4 missing.  perhaps I will create a PR

**Comment by DarioN1** [comment]
Thanks to support !
